version: '3.8'
services:
  node-dev:
    build: ./
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    restart: always
    working_dir: /app
    command: sh -c 'npx tsc; node dist/index.js'